name: size_finder
description: "A simple Flutter widget to find the size of your widget."
version: 0.0.1

homepage: https://ad.auliyaa.com
repository: https://github.com/dhiyaaulauliyaa/size_finder
issue_tracker: https://github.com/dhiyaaulauliyaa/size_finder/issues

topics:
  - size
  - widget
  
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
    
exclude:
 - docs/**

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0